# #devforge
command_timeout = 1000
# version: 1.0.0
add_newline = false

format = """
$os\
[ ](fg:#ffb300)$username\
[ ](fg:#f57c00)$directory\
[  ](fg:#ff7043)$git_branch$git_status\
[ ](fg:#8d6e63)$rust$nodejs$python\
$docker_context\
$time\
$line_break$character
"""

[character]
success_symbol = "[ ](bold yellow)"
error_symbol = "[ ](bold red)"

[username]
style_user = "fg:#ffb300"
show_always = true
style_root = 'black bold'
format = '[$user]($style) '
disabled = false

[directory]
style = "fg:#f57c00"
truncation_length = 2
truncation_symbol = " "

[git_branch]
symbol = ""
style = "fg:#ff7043"
format = "[$symbol $branch ]($style)"


[git_status]
style = "fg:#ff7043"
format = "[$all_status]($style)"
conflicted = '󱧴'
ahead = '󱦴 ${count}'
behind = '󱦶 ${count}'
diverged = ' 󱦸 󱦴${ahead_count} 󱦶${behind_count}'
up_to_date = ' 󱦺 '
untracked = ''
stashed = ''
modified = '󱦣 '
staged = '[ 󱫉\($count\)](bg:color_lime)'
renamed = '󱧬'
deleted = '󱫊 '

[python]
symbol = ""
style = "fg:#8d6e63"
format = "[ $symbol $version ]($style)"
python_binary = "python"

[nodejs]
symbol = ""
style = "fg:#616161"
format = "[ $symbol $version ]($style)"

[rust]
symbol = ""
style = "fg:#455a64"
format = "[ $symbol $version ]($style)"

[docker_context]
symbol = ""
style = "fg:#8d6e63"
format = "[ $symbol $context ]($style)"

[os]
disabled = false
style = "fg:#ffb300"
format = "[ $symbol ]($style)"

[os.symbols]
Macos = ""
Linux = ""
Windows = ""

[line_break]
disabled = true

[time]
disabled = false
time_format = "%H:%M"
style = "fg:#8d6e63"
format = "[ $time ]($style)"

