#sugarshell
command_timeout = 1000


format = """
[](fg:#ec407a)\
$os\
$username\
[ ](fg:#ec407a bg:#f06292)\
$directory\
[ ](fg:#f06292 bg:#ab47bc)\
$git_branch\
$git_status\
[ ](fg:#ab47bc bg:#ba68c8)\
$python\
$nodejs\
$rust\
[ ](fg:#ba68c8 bg:#f48fb1)\
$docker_context\
[ ](fg:#f48fb1 bg:#f8bbd0)\
$time\
[ ](fg:#f8bbd0)\
$line_break$character"""

[os]
style = "fg:white bg:#ec407a"
format = "[ $symbol ]($style)"
disabled = false

[os.symbols]
Macos = "󰀵"
Linux = "󰌽"
Ubuntu = "󰕈"
Windows = "󰍲"

[username]
show_always = true
style_user = "bg:#ec407a fg:white"
style_root = "bg:#ec407a fg:white"
format = '[ $user ]($style)'

[directory]
style = "fg:white bg:#f06292"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "  "  


[git_branch]
symbol = " "
style = "fg:white bg:#ab47bc"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "fg:white bg:#ab47bc"
format = '[ $all_status$ahead_behind ]($style)'
conflicted = '󱧴'
ahead = '󱦴 ${count}'
behind = '󱦶 ${count}'
diverged = ' 󱦸 󱦴${ahead_count} 󱦶${behind_count}'
up_to_date = '  '
untracked = ''
stashed = ''
modified = ' '
staged = '[ 󱫉\($count\)](bg:color_lime)'
renamed = '󱧬'
deleted = '󱫊 '

[python]
symbol = ""
style = "fg:white bg:#ba68c8"
format = '[ $symbol ($version) ]($style)'
python_binary = "python"

[nodejs]
symbol = ""
style = "fg:white bg:#ba68c8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:white bg:#ba68c8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "fg:white bg:#f48fb1"
format = '[ $symbol $context ]($style)'

[time]
disabled = false
time_format = "%H:%M"
style = "fg:#ba68c8 bg:#f8bbd0"
format = "[ 󰙉 $time ]($style)"

[line_break]
disabled = true

[character]
success_symbol = "[󰙴 ](bold fg:#ec407a)"
error_symbol = "[󰙊 ](bold red)"